version: '3.8'

services:
    server:
        image: continuumio/anaconda3
        volumes:
            - .:/project
        working_dir: /project/source
        command: >
          bash -c "/opt/conda/bin/pip3 install -r /project/requirements.txt
          && /opt/conda/bin/python3 main.py server"
        ports:
            - "5000:5000"
    client:
        image: continuumio/anaconda3
        volumes:
            - .:/project
        working_dir: /project/source
        command: >
          bash -c "/opt/conda/bin/pip3 install -r /project/requirements.txt
          && /opt/conda/bin/python3 main.py client"