name: Code Coverage
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.9'
      
    steps:
    - uses: actions/checkout@main
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./coverage1.xml,./coverage2.xml # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: false # optional (default = false)
        verbose: true # optional (default = false)

#     steps:
#     - uses: actions/checkout@main
#     - name: Setup Python
#       uses: actions/setup-python@main
#       with:
#         python-version: 3.9
#     - name: Generate coverage report
#       run: |
#         pip install coverage
#         pip install unittest
#         coverage run -m unittest discover --cov=./ --cov-report=xml
#         pytest 
#     - name: Upload coverage to Codecov
#       uses: codecov/codecov-action@v2
#       with:
#         token: ${{ secrets.CODECOV_TOKEN }}
#         directory: ./coverage/reports/
#         env_vars: OS,PYTHON
#         fail_ci_if_error: true
#         files: ./coverage1.xml,./coverage2.xml
#         flags: unittests
#         name: codecov-umbrella
#         path_to_write_report: ./coverage/codecov_report.txt
#         verbose: true
        
        
        
